parameters:
- name: testOS
  type: string
  values:
    - ubuntu2004
- name: uhdSrcDir
  type: string
- name: uhdArtifactSource
  type: string
  default: current

jobs:
- template: job-uhd-devtest.yml
  parameters:
    suiteName: 'rhombus'
    testOS: '${{ parameters.testOS }}'
    knownHost: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE+SZhHi7YOvHW6xmVGhhZGLtqlZoPkOqGdr5WqnmLBN root@ubuntu'
    toolset: 'make'
    uhdSrcDir: '${{ parameters.uhdSrcDir }}'
    uhdArtifactSource: '${{ parameters.uhdArtifactSource }}'
    redisHost: 'sdr-rhombus'
    dutMatrix:
      rhombus-x300-UBX-0:
        devType: 'x300'
        devModel: 'x300'
        devName: 'rhombus-x300-UBX-0'
        devSerial: '30A6019'
        devBus: 'ip'
        devAddr: '192.168.40.2'
        devFpga: 'HG,XG'
        devtestPattern: 'x3x0'
        jtagSerial: '2516350A6019'
        jtagServer: 'nitest@sdr-rhombus'
      rhombus-x310-UBX-0:
        devType: 'x300'
        devModel: 'x310'
        devName: 'rhombus-x310-UBX-0'
        devSerial: '3138EF5'
        devBus: 'ip'
        devAddr: '192.168.40.3'
        devFpga: 'HG,XG'
        devtestPattern: 'x3x0'
        jtagSerial: '251635138E98'
        jtagServer: 'nitest@sdr-rhombus'
      rhombus-x310-CBX-0:
        devType: 'x300'
        devModel: 'x310'
        devName: 'rhombus-x310-CBX-0'
        devSerial: '30796C2'
        devBus: 'ip'
        devAddr: '192.168.40.4'
        devFpga: 'HG,XG'
        devtestPattern: 'x3x0'
        jtagSerial: '2516350796C2'
        jtagServer: 'nitest@sdr-rhombus'
      rhombus-x310-WBX-0:
        devType: 'x300'
        devModel: 'x310'
        devName: 'rhombus-x310-WBX-0'
        devSerial: '30C5BFF'
        devBus: 'ip'
        devAddr: '192.168.40.5'
        devFpga: 'HG,XG'
        devtestPattern: 'x3x0'
        jtagSerial: '2516350C5BFF'
        jtagServer: 'nitest@sdr-rhombus'
      rhombus-x310-TWINRX-0:
        devType: 'x300'
        devModel: 'x310'
        devName: rhombus-x310-TWINRX-0
        devSerial: 'F43D13'
        devBus: 'ip'
        devAddr: '192.168.40.6'
        devFpga: 'HG,XG'
        devtestPattern: 'x3x0'
        jtagSerial: '251635F43D13'
        jtagServer: 'nitest@sdr-rhombus'
      rhombus-x300-SBX-0:
        devType: 'x300'
        devModel: 'x300'
        devName: rhombus-x300-SBX-0
        devSerial: '32244AD'
        devBus: 'ip'
        devAddr: '192.168.40.7'
        devFpga: 'HG,XG'
        devtestPattern: 'x3x0'
        jtagSerial: '2516352244AD'
        jtagServer: 'nitest@sdr-rhombus'

      rhombus-b210-0:
        devType: 'b200'
        devModel: 'b210'
        devName: rhombus-b210-0
        devSerial: '3218D0E'
        devBus: 'usb'
        devtestPattern: 'b2xx'
